version: 2
orbs:
  aws-cli: circleci/aws-cli@0.1.13
jobs:
  build:
    docker:
      - image: debian:stretch
        
    steps:
      - checkout

      - run:
          name: Who am I?
          command: aws cli get-caller-identity